name: cluemaster-roomcontroller-core
base: core20
version: '0.2'
summary: ClueMaster Room Controller
description: |
  Room Controller is a Linux Python appliation that connects physical devices to the escape room.
  The room controller reads inputs and sends commands to relays to controll and automate room functions.

grade: devel 
confinement: strict 

apps:
  room-controller:
    daemon: simple
    restart-condition: always
    command: bin/python3 $SNAP/roomcontroller-sourcecode/main.py

plugs:
  home:
  network:
  network-bind:
  hardware-observe:
  network-observe:

parts:
  copy-source-code:
    plugin: dump
    source: .
    organize:
      "static/prepare-launch": "bin/"

  room-controller:
    plugin: python
    source: .

    python-packages:
      - psutil
      - signalrcore
      - requests

    stage-packages:
      - libass9
      - locales
      - samba-libs
      - git
      - python3
      - bash
      
    organize:
      usr/lib/*/samba/*: usr/lib/

    stage:
      - -usr/lib/x86_64-linux-gnu/libc_malloc_debug.so
